### PR TITLE
Initial example structure

### PR DESCRIPTION
**Pull request by ZoranPandovski**
Initial structure for create, query and get metadata for mindsdb server predictors endpoint.

### CODE REVIEW

**Comment by George3d6** [comment]
The content is good but the way you are doing it is way to complex.

This is the stlye I ended up using for the edx course:

```
import requests
import json

root_url = 'http://localhost:47334'

# Spcify the training data and the value you want predicted
train_data_url = 'https://raw.githubusercontent.com/mindsdb/mindsdb-examples/master/benchmarks/heart_disease/processed_data/train.csv'
train_data = {
    'to_predict': 'target',
    'from_data': train_data_url
    }

# Run a statistical analysis of the data to gather insights about it
response = requests.request('GET', f'{root_url}/predictors/any/analyse_dataset', params=train_data)
print(response.text)

# Create a Predictor (this will automatically start training the Predictor with the training data specified to predicted the outputs)
predictor_name = 'heart_disease_predictor'
response = requests.request('PUT', f'{root_url}/predictors/{predictor_name}', json=train_data)
print(response.text)

# Get a prediction based on some incomplete data
test_data = {
    'when': {
        'age': '25',
        'sex': '0',
        'chol': '150',
        'thalach': '170',
        'exang': '0',
        'fbs': '0',
        'thal': '3',
    },
    'format_flag': 'new_explain' # The format of the returned predictions, new_explain is the best one currently, I recommend only using this, other format serve backwards compatibility purposes
}
response = requests.request('POST',f'{root_url}/predictors/{predictor_name}/predict', json=test_data)
first_prediction = response.json()[0]['target'] # Note: We only sent one prediction in the form of the `when` parameters, the array being returned will contain multiple predictions if more than one row/object is sent, the order of the predictions is the same as the ordering of the array being sent

predicted_value = first_prediction['predicted_value']
confidence_percentage = round(100* first_prediction['confidence'])
print(f'Predicted a value of {predicted_value} with a confidence of {confidence_percentage}%')
```

Could you transition the example to something like this and potentially add some more calls (e.g upload data source, analyze Predictor).

It's not that your code is incorrect, but for the purposes of a showcase I think it's much easier to step through the various called inlined sequentially rather than build a function for each of them.

**Comment by ZoranPandovski** [comment]
I've included a new file `showcase.py`. It includes the code structure provided by @George3d6, plus a call for getting metadata for predictor. Additionally, the Query part is dived into two sections related to improving the performance when more important features are included in the `when` clause.

**Comment by ZoranPandovski** [comment]
@George3d6 Please check the example. I will need to include an additional examples for Uploading datasource and train a predictor with ds.

**Comment by ZoranPandovski** [comment]
Added examples for `create` and `get` MindsDB Datasource. I've changed the dataset URL to point to the raw dataset that is not split to train and test. It contains 30% more rows and model accuracy is increased above 90%

**Comment by George3d6** [comment]
@ZoranPandovski keep pointing the url to train...accuracy doesn't matter that much, it's just an example after all and having a test/train split helps because we might want to demo predicting from datasource.

Anyway, merging this now, feel free to push further commits directly to master.

**Pull request merged**
